language: node_js
node_js:
- 12
env:
  global:
    - secure: TVsL8feJmx8WJTQQFQEt67tl57E5U7XTkTfvr3d7RloWfdmzD5wfdbG0+rrVBdlE0vDcYQaPtdgmb4KmFo4XL7u7ij6V3Mk8Wn9AY51j1AwcVrQ4wEUGgcZDti3GL90ou2h4gP0jg4y65E0nnwOb1rBu9wVOciXTn66XcvCxvF1qQgr9cGl4jcM5xc0e+x456PNRaClYH0qBxsTNdptnLMdldq50kZhpe6vuaQ9VOl1O4+gFnSNCi0+3oENuaULqscUOHrCHKCfQtLCg15fotdclaND0esiS/YjFJd8u0SJoB9IOsQ2VOcUfW1/Q/8dn0qYXlsRQELmGrgw6FdqL5tfjAqwOKmtfldz58qrFxj2HKu836VZ/HtJuXN/7h9ZsIRFV+2EbUnc+Q6FStZ2axuksRXYl8iounWHAMgTD35IzwgvZiqmOHjWOL6sVzLNIDKkUqVn1TTBWcgwkZ3koY7yM9RJqNO6HFtWXwwZ7exGo9FBge7lsGPQfFXUab1mijyx58VW4VFtTPLsDMtl3SC03oV10Wq8CWE7APWqQbRMvN8+WYLnKUmDtIRBL/4p4zJS98iaEvwTLnK3lR/Iqa42gb73fsuRxn79rvRiLF+8dBJg1AqbQEO9stzWfhsBKE3qAdD3xx4wpM1GeSz62W786DcZkhmuL7aG7YbO/E0U=
